### ISSUE TITLE
Required Ruby needs to be updated to 2.5

### ISSUE THREAD

**Issue by MasterSlowPoke** [captaincontrat/hubspot-api-ruby#11]
Hey all, thanks for all the hard work. I'm trying to integrate this into an older 2.4 app, but it will not work 100%. It throws an error anytime I try to update:

`NoMethodError: undefined method 'yield_self' for #<HTTParty::Response:0x007fa7b6ba6750>`

Looking into it,`yield_self` was added in Ruby 2.5.

Just putting this up here for anyone else upgrading a legacy app until the gemspec is updated.

Thanks again for all the work updating this!

**Comment by fonji** [comment]
Oh, thanks for the head's up!
As we test against nothing earlier than 2.7, I set that as a requirement. #12 
Better avoid other disappointments.

**Comment by fonji** [comment]
Released in 0.13.0
Thanks @MasterSlowPoke 
![image](https://user-images.githubusercontent.com/2310971/198324578-510611b2-b106-4f06-bbdd-e553fe50ed0f.png)

**Comment by fonji** [comment]
(BTW thanks for the laugh with https://github.com/MasterSlowPoke/CallOfDuty :joy: )
