### ISSUE TITLE
Let's find an organization name!

### ISSUE THREAD

**Issue by fonji** [captaincontrat/hubspot-api-ruby#15]
As @ur5us suggested [in a comment](https://github.com/captaincontrat/hubspot-api-ruby/pull/10#issuecomment-1280092392):
With contributors coming from outside Captain Contrat, it seems fair to move this code to another organization.
So let's start with finding a name!

Suggestions so far:
- HubSpotFriends
- HubspotApiRuby 
  - Note by @ur5us: HS probably won’t like that. I don't know why, and it's the name of the gem anyway :innocent: 
- ~~HubspotCommunity~~ is already taken
- HubspotRubyCommunity

Any other ideas? Opinions?

**Comment by Intrepidd** [comment]
My vote goes for `HubspotRubyCommunity`, simple, self explanatory

**Comment by Paul-Yves** [comment]
HubspotRubyCommunity

**Comment by adetkr** [comment]
`HubspotRubyCommunity`

**Comment by ur5us** [comment]
> Note by @ur5us: HS probably won’t like that. I don't know why, and it's the name of the gem anyway

The reason why is that it sounds too official for an organization IMO. With the **Community** suffix that should be a non issue from a legal point of view (disclaimer: I’m not a lawyer; better save than sorry in this context).

So as other people here, personally I’d go for **HubSpotRubyCommunity** but **HubSpotFriends** would work equally well, especially if there are plans/ideas around allowing other language libraries under the same umbrella org. But it’s probably a bit too much.

**Comment by fonji** [comment]
Thanks for the details @ur5us!

I think it's pretty clear we'll go for `HubspotRubyCommunity`.
Thanks everyone!
