### ISSUE TITLE
Undefined method `parsed_response in create_or_update method call

### ISSUE THREAD

**Issue by malindamiller** [captaincontrat/hubspot-api-ruby#18]
Hi, we are getting an error back from the `create_or_update` API call. Any suggestions?
<img width="756" alt="Screen Shot 2022-11-17 at 4 20 11 PM" src="https://user-images.githubusercontent.com/5913642/202562604-49f22815-df6f-4c3d-bb9e-6fbb40ec8109.png">

**Comment by fonji** [comment]
That's weird. Sorry for the delay. Did you get it to work since then?
Please note that this gem currently supports ruby 2.7+. It may be related to you version of ruby and/or HTTParty.

**Comment by malindamiller** [comment]
We are on ruby 2.6 so that could be the issue. We called those methods
directly so we could pass in the no_parse param until we can update our
ruby version.

**Comment by fonji** [comment]
Let me know if it still does not work when you upgrade!
I'll close for now, I'll reopen if this pops up again.
