### ISSUE TITLE
Hubspot API key deprecating

### ISSUE THREAD

**Issue by jamesfoley-snapraise** [captaincontrat/hubspot-api-ruby#19]
With API key's deprecating and the use of private apps being emphasized, will this package support that change?

https://developers.hubspot.com/docs/api/migrate-an-api-key-integration-to-a-private-app

**Comment by kez** [comment]
@jamesfoley-snapraise this project's README [calls out this deprecation](https://github.com/captaincontrat/hubspot-api-ruby#authentication-with-an-api-key) and also supports private app access token as an authentication method [detailed here](https://github.com/captaincontrat/hubspot-api-ruby#authentication-with-a-private-app-access-token)

**Comment by fonji** [comment]
Thanks @kez! Yes @jamesfoley-snapraise, this fork already supports private app tokens.
Also, [a warning will be displayed if you try to configure using an API key.](https://github.com/captaincontrat/hubspot-api-ruby/blob/master/lib/hubspot/config.rb#L35)
The merged PR is here if you want to take a look https://github.com/captaincontrat/hubspot-api-ruby/pull/7

We'll continue supporting API keys for a few months, as users can request an extension, but we'll drop the support eventually next year.

Have a nice day!
